[package]
name = "chat_client"
version = "0.1.0"
authors = ["oribenshir <oribenshir@gmail.com>"]
edition = "2018"

[dependencies]
ctrlc = "3.1.1"
byteorder = "1.3.1"
tlv_message = { path = "../tlv_message" }